version: "3.9"

services:
  webapp:
    container_name: one-review-api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
    - "5001:5001"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - Database__ConnectionStrings__DefaultConnection=Host=;Port=5432;Database=onereview;Username=postgres;Password=postgres;
    depends_on:
        db:
         condition: service_healthy
    
  db:
   container_name: onet-review-db    
   image: postgres:latest
   environment:
    - POSTGRES_DB=onereview
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   ports:
    - "5432:5432"
   # volumes:
   #  - postgres_data:/var/lib/postgresql/data # postgres storing ther data
   volumes:
    - ./.containers/database:/var/lib/postgresql/data
   healthcheck:
    test: ["CMD-SHELL", pg_isready -U postgres -d onereview]
    interval: 5s
    timeout: 5s
    retries: 5

# volumes:
#     postgres_data: