@host = http://localhost:5001
#@host = http://localhost:5227
@token = a


# @name create

POST {{host}}/products
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name":"MacBook Pro M3 Max",
  "Category": "Electronics",
  "SubCategory": "Laptops"
}

### get based on location header

GET {{create.response.headers.Location}}


###
GET http://localhost:5001/Products/d190d07f-9f13-459b-8a7d-7da7fd0d015c